"""initial_schema

Revision ID: bcf1da0dec28
Revises: 
Create Date: 2026-07-06 12:55:47.010675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcf1da0dec28'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('narrator_registry',
    sa.Column('narrator_id', sa.String(length=128), nullable=False),
    sa.Column('domain_tag', sa.String(length=128), nullable=False),
    sa.Column('narrator_type', sa.String(length=32), nullable=False),
    sa.Column('grade', sa.String(length=32), nullable=False),
    sa.Column('adalah_grade', sa.String(length=32), nullable=False),
    sa.Column('dabt_grade', sa.String(length=32), nullable=False),
    sa.Column('known_error_rate', sa.Float(), nullable=True, comment='NULL = uncalibrated; ordinal grade leads'),
    sa.Column('model_version', sa.String(length=128), nullable=True),
    sa.Column('model_family', sa.String(length=128), nullable=True, comment='For correlation (madār) detection'),
    sa.Column('upstream_source', sa.String(length=256), nullable=True, comment='Upstream source for correlation detection'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('narrator_id', 'domain_tag')
    )
    op.create_index('ix_narrator_registry_grade', 'narrator_registry', ['grade'], unique=False)
    op.create_index('ix_narrator_registry_is_active', 'narrator_registry', ['is_active'], unique=False)
    op.create_table('review_queue',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.String(length=128), nullable=False),
    sa.Column('page_slug', sa.String(length=256), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('chain_grade', sa.String(length=32), nullable=False, comment='ChainGrade enum value'),
    sa.Column('content_verdict', sa.String(length=32), nullable=False, comment='ContentVerdict enum value'),
    sa.Column('matrix_action', sa.String(length=64), nullable=False, comment='Action enum value'),
    sa.Column('conflicting_claim_ids', sa.JSON(), nullable=False, comment='List of conflicting claim IDs'),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('reviewer_id', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_review_queue_claim', 'review_queue', ['claim_id'], unique=False)
    op.create_index('ix_review_queue_created', 'review_queue', ['created_at'], unique=False)
    op.create_table('rijal_claims',
    sa.Column('claim_id', sa.String(length=128), nullable=False),
    sa.Column('page_slug', sa.String(length=256), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=False),
    sa.Column('narrator_chain', sa.JSON(), nullable=False, comment='Denormalized audit copy'),
    sa.Column('chain_grade', sa.String(length=32), nullable=True, comment='ChainGrade enum value; NULL until graded'),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True, comment='Lifecycle: supersession, not deletion'),
    sa.Column('superseded_by', sa.String(length=128), nullable=True, comment='claim_id of superseding claim'),
    sa.Column('chain_status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('claim_id')
    )
    op.create_index('ix_rijal_claims_chain_status', 'rijal_claims', ['chain_status'], unique=False)
    op.create_index('ix_rijal_claims_page_slug', 'rijal_claims', ['page_slug'], unique=False)
    op.create_table('chain_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.String(length=128), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('narrator_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=128), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('trace_id', sa.String(length=256), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transform_type', sa.String(length=32), nullable=False),
    sa.Column('domain', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['rijal_claims.claim_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chain_links_claim_step', 'chain_links', ['claim_id', 'step'], unique=True)
    op.create_index('ix_chain_links_narrator', 'chain_links', ['narrator_id'], unique=False)
    op.create_table('narrator_evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('narrator_id', sa.String(length=128), nullable=False),
    sa.Column('domain_tag', sa.String(length=128), nullable=False),
    sa.Column('evidence_type', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['narrator_id', 'domain_tag'], ['narrator_registry.narrator_id', 'narrator_registry.domain_tag'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_narrator_evidence_created', 'narrator_evidence', ['created_at'], unique=False)
    op.create_index('ix_narrator_evidence_narrator', 'narrator_evidence', ['narrator_id', 'domain_tag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_narrator_evidence_narrator', table_name='narrator_evidence')
    op.drop_index('ix_narrator_evidence_created', table_name='narrator_evidence')
    op.drop_table('narrator_evidence')
    op.drop_index('ix_chain_links_narrator', table_name='chain_links')
    op.drop_index('ix_chain_links_claim_step', table_name='chain_links')
    op.drop_table('chain_links')
    op.drop_index('ix_rijal_claims_page_slug', table_name='rijal_claims')
    op.drop_index('ix_rijal_claims_chain_status', table_name='rijal_claims')
    op.drop_table('rijal_claims')
    op.drop_index('ix_review_queue_created', table_name='review_queue')
    op.drop_index('ix_review_queue_claim', table_name='review_queue')
    op.drop_table('review_queue')
    op.drop_index('ix_narrator_registry_is_active', table_name='narrator_registry')
    op.drop_index('ix_narrator_registry_grade', table_name='narrator_registry')
    op.drop_table('narrator_registry')
    # ### end Alembic commands ###
